FROM ethereum/client-go:latest

RUN mkdir -p /opt/blockchain/data/keystore \
  && mkdir -p /opt/blockchain/config

COPY genesis.json /opt/blockchain/config/
COPY genesis-pw /opt/blockchain/config/
COPY UTC--2020-10-08T16-19-41.212110077Z--1c2f8378de9efad88398299cf7b41cdacf2af215 /opt/blockchain/data/keystore/

RUN cd /opt/blockchain/config \
  && geth account new --datadir /opt/blockchain/data --password /opt/blockchain/config/genesis-pw \
  && geth init --datadir /opt/blockchain/data genesis.json
