--- # snode sources

- name: XR_PROXY
  type: base
  image: blocknetdx/exrproxy:latest
  volume: /snode
  disk: 1
  ram: 1
  cpu: 1

- name: SNODE 
  type: base
  image: blocknetdx/servicenode:latest 
  volume: /snode
  disk: 5
  ram: 2
  cpu: 2

- name: PAYMENT
  type: base
  payment_xquery: 35
  payment_tier1: 35
  payment_tier2: 200
  discount_ablock: 20
  discount_aablock: 0      
  discount_sysblock: 10      
  image: blocknetdx/eth-payment-processor:latest
  volume: /snode
  disk: 1
  ram: 1
  cpu: 1

- name: ETH
  type: evm_chain
  image: ethereum/client-go:latest 
  volume: /snode
  disk: 12000
  ram: 16
  cpu: 6

- name: AVAX
  type: evm_chain 
  image: avaplatform/avalanchego:latest
  volume: /snode
  disk: 1100
  ram: 16
  cpu: 6

- name: BTC 
  type: chain
  image: blocknetdx/bitcoin:v0.20.0
  volume: /snode
  disk: 550
  ram: 5
  cpu: 4

- name: DASH 
  type: chain
  image: blocknetdx/dash:v19.1.0
  volume: /snode
  disk: 38
  ram: 6
  cpu: 4

- name: DGB 
  type: chain
  image: blocknetdx/digibyte:v7.17.2
  volume: /snode
  disk: 34
  ram: 5
  cpu: 4

- name: DOGE 
  type: chain
  image: blocknetdx/dogecoin:v1.14.5
  volume: /snode
  disk: 68
  ram: 5
  cpu: 4

- name: DOGEC 
  type: chain
  image: blocknetdx/dogecash:5.4.4
  volume: /snode
  disk: 4
  ram: 5
  cpu: 4

- name: GBX 
  type: chain
  image: blocknetdx/gobyte:v0.16.2.1
  volume: /snode
  disk: 3
  ram: 5
  cpu: 4

- name: LBC 
  type: chain
  image: blocknetdx/lbrycredits:v0.17.4.6
  volume: /snode
  disk: 160
  ram: 5
  cpu: 4

- name: LTC 
  type: chain
  image: blocknetdx/litecoin:v0.18.1
  volume: /snode
  disk: 100
  ram: 5
  cpu: 4

- name: MUE 
  type: chain
  image: blocknetdx/monetaryunit:v2.3.0
  volume: /snode
  disk: 5
  ram: 5
  cpu: 4

- name: PHR 
  type: chain
  image: blocknetdx/phore:v1.8.0
  volume: /snode
  disk: 8
  ram: 5
  cpu: 4

- name: PIVX 
  type: chain
  image: blocknetdx/pivx:v5.5.0
  volume: /snode
  disk: 21
  ram: 5
  cpu: 4

- name: RVN 
  type: chain
  image: blocknetdx/ravencoin:v4.3.2.1
  volume: /snode
  disk: 36
  ram: 5
  cpu: 4

- name: SCC 
  type: chain
  image: blocknetdx/stakecubecoin:v3.1.0
  volume: /snode
  disk: 4
  ram: 8
  cpu: 4

- name: SYS 
  type: hybrid
  image: blocknetdx/syscoin:v4.4.2
  volume: /snode
  disk: 11
  ram: 5
  cpu: 4

- name: UNO 
  type: chain
  image: blocknetdx/unobtanium:v0.11.5
  volume: /snode
  disk: 5
  ram: 5
  cpu: 4

- name: NEVM
  type: evm_chain
  image: blocknetdx/syscoin4:v4.3.0
  volume: /snode
  disk: 11
  ram: 5
  cpu: 4

- name: UTXO_PLUGIN
  type: utxo_plugin
  utxo_plugin_image: blocknetdx/utxo-plugin:latest
  plugin_adapter_image: blocknetdx/plugin-adapter:latest
  exclude_chains: # The utxo-plugin module doesn't yet work for the following chains:
    - PHR
    - LBC
    - RVN
    - DGB
  volume: /snode
  disk: 200
  ram: 32
  cpu: 8

- name: HYDRA
  type: app
  free: False
  disk: 1
  ram: 16
  cpu: 4
  chains:
    - name: AVAX
    - name: ETH
    - name: NEVM
      
- name: XQUERY
  type: app
  volume: /snode
  disk: 15
  ram: 16
  cpu: 32
  dexs:
    - name: AVAX_PANGOLIN
      target_sleep_time: 30
      num_safety_blocks: 10
    - name: NEVM_PEGASYS
      target_sleep_time: 60
      num_safety_blocks: 5
#    - name: ETH_UNISWAP_V2
#      target_sleep_time: 30
#      num_safety_blocks: 10
#    - name: ETH_UNISWAP_V3
#      target_sleep_time: 30
#      num_safety_blocks: 10
