--- # snode sources

- name: XR_PROXY
  type: base
  image: blocknetdx/exrproxy:latest
  volume: /snode
  disk: 1
  ram: 1
  cpu: 1

- name: SNODE 
  type: base
  image: blocknetdx/servicenode:latest 
  volume: /snode
  disk: 5
  ram: 2
  cpu: 2

- name: PAYMENT
  type: base
  payment_tier1: 35
  payment_tier2: 200
  discount_ablock: 20
  discount_aablock: 0      
  discount_sysblock: 10      
  image: blocknetdx/eth-payment-processor:latest
  volume: /snode
  disk: 1
  ram: 1
  cpu: 1

- name: ETH
  type: evm_chain
  image: ethereum/client-go:latest 
  volume: /snode
  disk: 12000
  ram: 16
  cpu: 6

- name: AVAX
  type: evm_chain 
  image: avaplatform/avalanchego:latest
  volume: /snode
  disk: 620
  ram: 16
  cpu: 6

- name: BTC 
  type: chain
  image: blocknetdx/bitcoin:v0.20.0
  volume: /snode
  disk: 500
  ram: 5
  cpu: 4

- name: DASH 
  type: chain
  image: blocknetdx/dash:v0.17.0.3
  volume: /snode
  disk: 37
  ram: 6
  cpu: 4

- name: DGB 
  type: chain
  image: blocknetdx/digibyte:v7.17.2
  volume: /snode
  disk: 33
  ram: 5
  cpu: 4

- name: DOGE 
  type: chain
  image: blocknetdx/dogecoin:v1.14.5
  volume: /snode
  disk: 63
  ram: 5
  cpu: 4

- name: DOGEC 
  type: chain
  image: blocknetdx/dogecash:5.4.4
  volume: /snode
  disk: 4
  ram: 5
  cpu: 4

- name: GBX 
  type: chain
  image: blocknetdx/gobyte:v0.16.2.1
  volume: /snode
  disk: 3
  ram: 5
  cpu: 4

- name: LBC 
  type: chain
  image: blocknetdx/lbrycredits:v0.17.4.6
  volume: /snode
  disk: 150
  ram: 5
  cpu: 4

- name: LTC 
  type: chain
  image: blocknetdx/litecoin:v0.18.1
  volume: /snode
  disk: 85
  ram: 5
  cpu: 4

- name: MUE 
  type: chain
  image: blocknetdx/monetaryunit:v2.3.0
  volume: /snode
  disk: 5
  ram: 5
  cpu: 4

- name: PHR 
  type: chain
  image: blocknetdx/phore:v1.8.0
  volume: /snode
  disk: 8
  ram: 5
  cpu: 4

- name: PIVX 
  type: chain
  image: blocknetdx/pivx:v5.3.2
  volume: /snode
  disk: 21
  ram: 5
  cpu: 4

- name: RVN 
  type: chain
  image: blocknetdx/ravencoin:v4.3.2.1
  volume: /snode
  disk: 31
  ram: 5
  cpu: 4

- name: SCC 
  type: chain
  image: blocknetdx/stakecubecoin:v3.1.0
  volume: /snode
  disk: 4
  ram: 8
  cpu: 4

- name: SYS 
  type: hybrid
  image: blocknetdx/syscoin4:v4.3.0
  volume: /snode
  disk: 9
  ram: 5
  cpu: 4

- name: NEVM
  type: evm_chain
  image: blocknetdx/syscoin4:v4.3.0
  volume: /snode
  disk: 9
  ram: 5
  cpu: 4


- name: UNO 
  type: chain
  image: blocknetdx/unobtanium:v0.11.5
  volume: /snode
  disk: 5
  ram: 5
  cpu: 4

- name: HYDRA
  type: app
  free: False
  disk: 1
  ram: 16
  cpu: 4
  chains:
    - name: AVAX
    - name: ETH
    - name: NEVM
      
- name: XQUERY
  type: app
  volume: /snode
  disk: 5
  ram: 16
  cpu: 32
  graph: AVAX_ETH_NEVM
  endpoint: /indexer
  chains:
    - name: AVAX_PANGOLIN
      abi: pangolinRouter.json
      query:
        - name: Withdrawal
        - name: Deposit
        - name: Approval
        - name: Burn
        - name: Mint
        - name: Swap
        - name: Sync
        - name: Transfer
      address:
      - name: Pangolin_Router
        address: '0xE54Ca86531e17Ef3616d22Ca28b0D458b6C89106'
      historical:
      - fromBlock: "57347"
    - name: ETH_UNISWAP_v2
      abi: uniswapRouter_v2.json
      query:
        - name: Withdrawal
        - name: Deposit
        - name: Approval
        - name: Burn
        - name: Mint
        - name: Swap
        - name: Sync
        - name: Transfer
      address:
      - name: Uniswap_Router_v2
        address: '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D'
      historical:
      - fromBlock: "10207858"
    - name: ETH_UNISWAP_v3
      abi: uniswapRouter_v3.json
      query:
        - name: Withdrawal
        - name: Deposit
        - name: Approval
        - name: Burn
        - name: Mint
        - name: Swap
        - name: Sync
        - name: Transfer
      address:
      - name: Uniswap_Router_v3
        address: '0xe592427a0aece92de3edee1f18e0157c05861564'
      historical:
      - fromBlock: "12369634"
    - name: NEVM_PEGASYS
      #rpc_host: https://rpc.syscoin.org/
      abi: pegasysRouter.json
      query:
        - name: Withdrawal
        - name: Deposit
        - name: Approval
        - name: Burn
        - name: Mint
        - name: Swap
        - name: Sync
        - name: Transfer
      address:
      - name: Pegasys_Router
        address: '0x017dAd2578372CAEE5c6CddfE35eEDB3728544C4'
      historical:
      - fromBlock: "38202"
